import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";
const source = readFileSync(new URL("../lib/security.ts", import.meta.url), "utf8");
const output = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText;
const { methodAllowed, securityHeaders } = await import(`data:text/javascript;base64,${Buffer.from(output).toString("base64")}`);
assert.equal(methodAllowed("GET"), true);
assert.equal(methodAllowed("HEAD"), true);
for (const method of ["POST", "PUT", "DELETE", "PATCH", "OPTIONS"]) assert.equal(methodAllowed(method), false);
assert.throws(() => securityHeaders("bad; script-src *"));
const nonce = "0123456789abcdef0123456789abcdef";
const headers = securityHeaders(nonce);
assert.ok(headers["Content-Security-Policy"].includes(`script-src 'self' 'nonce-${nonce}'`));
assert.ok(!headers["Content-Security-Policy"].includes("unsafe-eval"));
assert.ok(headers["Content-Security-Policy"].includes("object-src 'none'"));
assert.equal(headers["X-Content-Type-Options"], "nosniff");
const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");
assert.ok(!/dangerouslySetInnerHTML|\.innerHTML|\beval\(/.test(page));
assert.ok(!/\bfetch\(|localStorage|sessionStorage/.test(page));
console.log("Security checks passed: methods, CSP, nonce validation, MIME protection, and safe input rendering.");
