"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Boxes, SlidersHorizontal, MousePointer2, LayoutGrid, Search, Moon, Sun, RotateCcw, Plus, Check, Bell, ShieldCheck, Sparkles, ChevronDown, Minus, Info } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogHeader, DialogTrigger, DialogClose } from "@/components/ui/dialog";
import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell } from "@/components/ui/table";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from "@/components/ui/tooltip";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu";
import { Sidebar, SidebarProvider } from "@/components/ui/sidebar";
import { Skeleton } from "@/components/ui/skeleton";
import { toast, Toaster } from "sonner";

const initialRows = [
 {id:1,name:"Olivia Rhye",email:"olivia@example.com",role:"Designer",status:"Active",initials:"OR",color:"purple"},
 {id:2,name:"Phoenix Baker",email:"phoenix@example.com",role:"Developer",status:"Active",initials:"PB",color:"blue"},
 {id:3,name:"Lana Steiner",email:"lana@example.com",role:"Designer",status:"Invited",initials:"LS",color:"pink"},
 {id:4,name:"Demi Wilkinson",email:"demi@example.com",role:"Manager",status:"Active",initials:"DW",color:"orange"},
 {id:5,name:"Drew Cano",email:"drew@example.com",role:"Developer",status:"Inactive",initials:"DC",color:"green"},
 {id:6,name:"Natali Craig",email:"natali@example.com",role:"Manager",status:"Invited",initials:"NC",color:"blue"}
];
const sections=[{id:"buttons",label:"Buttons & actions",icon:MousePointer2},{id:"inputs",label:"Inputs & selection",icon:SlidersHorizontal},{id:"data",label:"Tables & data",icon:LayoutGrid},{id:"feedback",label:"Feedback & overlays",icon:Bell}];
function Card({id,number,title,description,children,tag}:{id?:string;number:string;title:string;description:string;children:React.ReactNode;tag:string}) {return <section id={id} className="demo-card"><div className="card-heading"><div><span className="section-number">{number}</span><h2>{title}</h2><p>{description}</p></div><span className="code-tag">{tag}</span></div>{children}</section>}
function validate(n:string,e:string){if(!n.trim()||n.trim().length>60)return "Enter a name between 1 and 60 characters.";if(e.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))return "Enter a valid email address.";return "";}
export default function Home(){
 const [dark,setDark]=useState(false),[count,setCount]=useState(0),[busy,setBusy]=useState(false),[checked,setChecked]=useState(true),[notifications,setNotifications]=useState(true),[plan,setPlan]=useState("starter"),[volume,setVolume]=useState(64),[name,setName]=useState("Alex Morgan"),[email,setEmail]=useState(""),[note,setNote]=useState(""),[role,setRole]=useState("Designer"),[formError,setFormError]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("All statuses"),[rows,setRows]=useState(initialRows),[selected,setSelected]=useState<number[]>([]),[ascending,setAscending]=useState(true),[page,setPage]=useState(1),[tab,setTab]=useState("preview"),[active,setActive]=useState("buttons"),[dialogOpen,setDialogOpen]=useState(false),[inviteName,setInviteName]=useState(""),[inviteEmail,setInviteEmail]=useState(""),[inviteError,setInviteError]=useState("");
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{document.documentElement.classList.toggle("dark",dark);return()=>document.documentElement.classList.remove("dark")},[dark]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 const filtered=useMemo(()=>rows.filter(r=>(filter==="All statuses"||r.status===filter)&&`${r.name} ${r.email} ${r.role}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>ascending?a.name.localeCompare(b.name):b.name.localeCompare(a.name)),[rows,query,filter,ascending]);
 const pages=Math.max(1,Math.ceil(filtered.length/5)),currentPage=Math.min(page,pages),visible=filtered.slice((currentPage-1)*5,currentPage*5),allSelected=visible.length>0&&visible.every(r=>selected.includes(r.id)),someSelected=visible.some(r=>selected.includes(r.id));
 function reset(){if(timer.current)clearTimeout(timer.current);setCount(0);setBusy(false);setChecked(true);setNotifications(true);setPlan("starter");setVolume(64);setName("Alex Morgan");setEmail("");setNote("");setRole("Designer");setFormError("");setQuery("");setFilter("All statuses");setRows(initialRows);setSelected([]);setAscending(true);setPage(1);setTab("preview");setDark(false);setInviteName("");setInviteEmail("");setInviteError("");setDialogOpen(false);toast.success("Playground reset")}
 function simulateSave(){setBusy(true);timer.current=setTimeout(()=>{setBusy(false);toast.success("Demo changes saved",{description:"This is a simulation. Nothing was sent to a server."})},1000)}
 function invite(e:React.FormEvent){e.preventDefault();const error=validate(inviteName,inviteEmail);setInviteError(error);if(error)return;if(rows.length>=50){setInviteError("The demo supports up to 50 members. Reset to start again.");return}if(rows.some(r=>r.email.toLowerCase()===inviteEmail.trim().toLowerCase())){setInviteError("That email already exists in the demo.");return}setRows(r=>[...r,{id:Math.max(...r.map(x=>x.id),0)+1,name:inviteName.trim(),email:inviteEmail.trim(),role:"Designer",status:"Invited",initials:inviteName.trim().slice(0,2).toUpperCase(),color:"purple"}]);setDialogOpen(false);setInviteName("");setInviteEmail("");setInviteError("");setQuery("");setFilter("Invited");setPage(1);toast.success("Demo member added",{description:"No real invitation was sent."})}
 useEffect(()=>{
  type Registry={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>Promise<object>},options:{signal:AbortSignal})=>void|Promise<void>};
  const registry=(document as Document&{modelContext?:Registry}).modelContext;if(!registry)return;const lifecycle=new AbortController();
  try{Promise.resolve(registry.registerTool({name:"filter_demo_members",description:"Filter the visible demo member table by text and status.",inputSchema:{type:"object",properties:{query:{type:"string",maxLength:100},status:{type:"string",enum:["All statuses","Active","Invited","Inactive"]}},required:["query","status"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input){const v=input as {query?:unknown;status?:unknown};if(!v||typeof v!=="object"||Object.keys(v).some(k=>!["query","status"].includes(k))||typeof v.query!=="string"||v.query.length>100||typeof v.status!=="string"||!["All statuses","Active","Invited","Inactive"].includes(v.status))throw new Error("Invalid member filter");setQuery(v.query);setFilter(v.status);setPage(1);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {query:v.query,status:v.status}}},{signal:lifecycle.signal})).catch(()=>{})}catch{/* Optional browser capability. */}return()=>lifecycle.abort();
 },[]);
 return <TooltipProvider><SidebarProvider className="app-shell"><Sidebar collapsible="none" className="side-nav"><a className="brand" href="#"><span className="brand-mark"><Boxes size={22}/></span>component<span className="brand-light">lab</span></a><div className="nav-caption">PLAYGROUND</div><nav aria-label="Component sections">{sections.map(s=><a key={s.id} href={`#${s.id}`} className={active===s.id?"nav-link active":"nav-link"} onClick={()=>setActive(s.id)}><s.icon size={18}/>{s.label}</a>)}</nav><div className="sidebar-note"><span className="mini-logo">⚛</span><h3>Small pieces. Real possibilities.</h3><p>Explore the building blocks of an interactive React interface.</p><span className="version">React 19 · UI playground</span></div><div className="sidebar-footer"><ShieldCheck size={17}/><span>Local demo data</span></div></Sidebar>
 <div className="main-wrap"><header className="topbar"><div className="breadcrumb">Playground <span>/</span><strong>Overview</strong></div><div className="top-actions"><Badge variant="outline" className="demo-badge">Interactive demo</Badge><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" aria-label={dark?"Use light theme":"Use dark theme"} onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</Button></TooltipTrigger><TooltipContent>Switch theme</TooltipContent></Tooltip><span className="profile-avatar">AM</span></div></header><main id="main"><div className="page-heading"><div><div className="eyebrow">THE INTERACTIVE TOOLKIT</div><h1>Component playground<span>.</span></h1><p>A little of everything. Click, toggle, type — see what happens.</p></div><Button variant="outline" onClick={reset}><RotateCcw size={16}/>Reset playground</Button></div>
 <div className="overview-strip"><div><span className="strip-icon"><LayoutGrid size={20}/></span><div><strong>Everyday UI essentials</strong><span>One place to experiment</span></div></div><div><span className="strip-icon violet"><MousePointer2 size={20}/></span><div><strong>Real interactions</strong><span>Powered by React state</span></div></div><div><span className="strip-icon mint"><ShieldCheck size={20}/></span><div><strong>Browser-only data</strong><span>Reset anytime, no account needed</span></div></div></div>
 <div className="component-grid"><Card id="buttons" number="01" title="Buttons & actions" description="Different emphasis. Same satisfying click." tag="Buttons"><div className="example-label">BUTTON VARIANTS</div><div className="button-row"><Button onClick={()=>toast.success("Primary action clicked")}>Primary button</Button><Button variant="secondary" onClick={()=>toast("Secondary action clicked")}>Secondary</Button><Button variant="outline" onClick={()=>toast("Outline action clicked")}>Outline</Button><Button variant="ghost" onClick={()=>toast("Ghost action clicked")}>Ghost</Button></div><div className="button-row"><Button size="sm" onClick={()=>toast.success("Icon button clicked")}><Plus size={15}/>With icon</Button><Button variant="outline" disabled>Disabled</Button><Button variant="outline" disabled={busy} onClick={simulateSave}>{busy?<span className="spinner"/>:<Check size={15}/>} {busy?"Saving…":"Simulate save"}</Button></div><div className="inset-demo"><div><span className="example-label">REACTIVE COUNTER</span><p>A click, a state update, a fresh render.</p></div><div className="counter"><Button variant="outline" size="icon" aria-label="Decrease counter" disabled={count<=0} onClick={()=>setCount(c=>Math.max(0,c-1))}><Minus/></Button><output aria-live="polite">{count}</output><Button variant="outline" size="icon" aria-label="Increase counter" disabled={count>=999} onClick={()=>setCount(c=>Math.min(999,c+1))}><Plus/></Button></div></div></Card>
 <Card id="inputs" number="02" title="Choices & controls" description="A few ways to make it your own." tag="Selection"><div className="choices-grid"><div><div className="example-label">CHECKBOXES</div><label className="control-label"><Checkbox checked={checked} onCheckedChange={v=>setChecked(v===true)}/>Enable extra features</label><label className="control-label muted"><Checkbox disabled/>Coming soon</label><div className="example-label spaced">SWITCH</div><label className="control-label"><Switch checked={notifications} onCheckedChange={setNotifications}/>Notifications<span className="state-text">{notifications?"On":"Off"}</span></label></div><div><div className="example-label">RADIO GROUP</div><RadioGroup value={plan} onValueChange={setPlan}><label className="control-label"><RadioGroupItem value="starter"/>Starter<span className="muted">Free</span></label><label className="control-label"><RadioGroupItem value="pro"/>Pro<span className="muted">$12 / mo</span></label></RadioGroup><div className="slider-label"><span className="example-label">SLIDER</span><output>{volume}%</output></div><Slider aria-label="Preview progress" value={[volume]} max={100} step={1} onValueChange={v=>setVolume(v[0])}/></div></div><div className="state-summary"><span className="tiny-dot"/>Selected: {plan==="pro"?"Pro":"Starter"} plan · {checked?"Extra features enabled":"Extra features disabled"}</div></Card>
 <Card number="03" title="Forms & inputs" description="Controlled fields with instant feedback." tag="Forms"><form onSubmit={e=>{e.preventDefault();const error=validate(name,email);setFormError(error);if(!error)toast.success("Profile validated",{description:"Your demo profile stays in this page."})}}><div className="form-grid"><label>Full name<Input maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" autoComplete="off" required/></label><label>Role<Select value={role} onValueChange={setRole}><SelectTrigger className="full-width" aria-label="Profile role"><SelectValue/></SelectTrigger><SelectContent>{["Designer","Developer","Manager"].map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select></label></div><label className="field-label">Email address<Input type="email" maxLength={254} placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="off" required aria-describedby={formError?"form-error":undefined}/></label><label className="field-label">A short note<span className="muted">Optional</span><Textarea maxLength={300} placeholder="What are you working on?" value={note} onChange={e=>setNote(e.target.value)} rows={2}/></label><div className="form-footer"><span className="muted">{note.length}/300 characters</span><Button size="sm" type="submit">Save profile</Button></div>{formError&&<p id="form-error" className="error-text" role="alert">{formError}</p>}<div className="input-preview"><span>LIVE PREVIEW</span><strong>{name||"Your name"}</strong><span>{role}</span>{note&&<p>{note}</p>}</div></form></Card>
 <Card id="feedback" number="04" title="Feedback & overlays" description="Keep people informed, without the noise." tag="Feedback"><div className="notice"><Info size={18}/><div><strong>You’re in a playground</strong><p>Try every control. Changes disappear on refresh.</p></div></div><div className="example-label spaced">BADGES & STATUS</div><div className="badge-row"><Badge className="status active-status">Active</Badge><Badge className="status invited-status">Pending</Badge><Badge variant="secondary">Neutral</Badge><Badge variant="outline">Outline</Badge></div><div className="slider-label"><span className="example-label">PROGRESS</span><span className="muted">{volume}% complete</span></div><Progress value={volume} aria-label="Demo completion"/><p className="helper">Connected to the slider in Choices & controls.</p><div className="button-row"><Dialog><DialogTrigger asChild><Button variant="outline" size="sm"><LayoutGrid size={15}/>Open dialog</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>A little room to focus</DialogTitle><DialogDescription>This accessible dialog traps keyboard focus. Press Escape or use Close to return to the playground.</DialogDescription></DialogHeader><DialogClose asChild><Button>Close dialog</Button></DialogClose></DialogContent></Dialog><Button variant="outline" size="sm" onClick={()=>toast.success("Looking good!",{description:"This is a toast notification."})}><Bell size={15}/>Show toast</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="sm">More<ChevronDown size={15}/></Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onClick={()=>toast("Info notification",{description:"Dropdown menus support keyboard navigation."})}>Show information</DropdownMenuItem><DropdownMenuItem onClick={()=>toast.error("Example error",{description:"This is simulated; no operation failed."})}>Show error state</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></Card></div>
 <Card id="data" number="05" title="Tables & data" description="A small team, a useful set of interactions." tag="Data table"><div className="table-toolbar"><div className="search-field"><Search size={17}/><Input aria-label="Search team members" maxLength={100} placeholder="Search members…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></div><Select value={filter} onValueChange={v=>{setFilter(v);setPage(1)}}><SelectTrigger aria-label="Filter by status"><SlidersHorizontal size={15}/><SelectValue/></SelectTrigger><SelectContent>{["All statuses","Active","Invited","Inactive"].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Dialog open={dialogOpen} onOpenChange={v=>{setDialogOpen(v);setInviteError("")}}><DialogTrigger asChild><Button size="sm"><Plus size={15}/>Add member</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add a demo member</DialogTitle><DialogDescription>Add a sample row to the table. No email will be sent.</DialogDescription></DialogHeader><form onSubmit={invite} className="invite-form"><label>Name<Input required autoComplete="off" maxLength={60} value={inviteName} onChange={e=>setInviteName(e.target.value)}/></label><label>Email<Input required type="email" autoComplete="off" maxLength={254} value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/></label>{inviteError&&<p className="error-text" role="alert">{inviteError}</p>}<Button type="submit">Add demo member</Button></form></DialogContent></Dialog></div>
 <Table><TableHeader><TableRow><TableHead className="check-cell"><Checkbox aria-label="Select visible members" checked={allSelected?true:someSelected?"indeterminate":false} onCheckedChange={v=>setSelected(s=>v===true?[...new Set([...s,...visible.map(r=>r.id)])]:s.filter(id=>!visible.some(r=>r.id===id)))}/></TableHead><TableHead aria-sort={ascending?"ascending":"descending"}><button className="sort-button" onClick={()=>setAscending(!ascending)}>Name<span>{ascending?"↑":"↓"}</span></button></TableHead><TableHead>Role</TableHead><TableHead>Status</TableHead><TableHead className="right">Action</TableHead></TableRow></TableHeader><TableBody>{visible.map(r=><TableRow key={r.id} data-state={selected.includes(r.id)?"selected":undefined}><TableCell><Checkbox aria-label={`Select ${r.name}`} checked={selected.includes(r.id)} onCheckedChange={v=>setSelected(s=>v===true?[...s,r.id]:s.filter(id=>id!==r.id))}/></TableCell><TableCell><div className="member-cell"><span className={`member-avatar ${r.color}`}>{r.initials}</span><div><strong>{r.name}</strong><span>{r.email}</span></div></div></TableCell><TableCell>{r.role}</TableCell><TableCell><Badge className={`status ${r.status.toLowerCase()}-status`}>{r.status}</Badge></TableCell><TableCell className="right"><Button variant="ghost" size="sm" onClick={()=>toast(r.name,{description:`${r.role} · ${r.status} · ${r.email}`})}>View</Button></TableCell></TableRow>)}{!visible.length&&<TableRow><TableCell colSpan={5}><div className="empty-state"><Search/><strong>No members found</strong><p>Try another name or change the status filter.</p><Button variant="outline" size="sm" onClick={()=>{setQuery("");setFilter("All statuses")}}>Clear filters</Button></div></TableCell></TableRow>}</TableBody></Table><div className="table-footer"><span>{selected.length>0?`${selected.length} selected · `:""}{filtered.length} members · Page {currentPage} of {pages}</span><div><Button variant="outline" size="sm" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}>Previous</Button><Button variant="outline" size="sm" disabled={currentPage>=pages} onClick={()=>setPage(currentPage+1)}>Next</Button></div></div></Card>
 <div className="component-grid bottom-grid"><Card number="06" title="Tabs & content" description="Different views, without leaving the page." tag="Tabs"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="preview">Preview</TabsTrigger><TabsTrigger value="details">Details</TabsTrigger><TabsTrigger value="loading">Loading state</TabsTrigger></TabsList><TabsContent value="preview"><div className="preview-tile"><span className="tile-icon"><Sparkles size={23}/></span><h3>Make something great.</h3><p>Your next interface starts with a few small pieces.</p><Badge variant="outline">Ready to explore</Badge></div></TabsContent><TabsContent value="details"><div className="tab-details"><h3>Built for interaction</h3><p>React state connects the controls to their previews. Components update without reloading the page.</p><p>Try the counter, form preview, table filters, and shared slider.</p></div></TabsContent><TabsContent value="loading"><div className="skeleton-demo" aria-label="Example loading placeholder"><Skeleton className="h-12 w-12 rounded-full"/><Skeleton className="h-5 w-3/4"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-2/3"/><p className="helper">A preview of a loading placeholder.</p></div></TabsContent></Tabs></Card><Card number="07" title="A few useful details" description="Answers, tucked away until you need them." tag="Accordion"><Accordion type="single" collapsible defaultValue="one"><AccordionItem value="one"><AccordionTrigger>What can I try here?</AccordionTrigger><AccordionContent>Click buttons, type in forms, switch themes, filter and select table rows, open dialogs, and move the slider. The progress bar updates with it.</AccordionContent></AccordionItem><AccordionItem value="two"><AccordionTrigger>Is my information saved?</AccordionTrigger><AccordionContent>Demo fields and table changes stay in browser memory only. Refresh the page or choose Reset playground to start over.</AccordionContent></AccordionItem><AccordionItem value="three"><AccordionTrigger>How is user input handled?</AccordionTrigger><AccordionContent>Your text is rendered as text, including any HTML tags. Fields have length limits, forms validate names and emails, and the demo has no database or server write operations.</AccordionContent></AccordionItem></Accordion></Card></div><footer className="page-footer"><span><Boxes size={16}/>Component Lab</span><span>Built with React. Made to be explored.</span><a href="#main">Back to top</a></footer></main></div></SidebarProvider><Toaster richColors position="bottom-right" theme={dark?"dark":"light"}/></TooltipProvider>;
}

